import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import Login from "./login";
import Japanese from "./japanese";
import Programming from "./programming";

export const metadata: Metadata = {
  title: "Taami edu",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
       {children}
      </body>
    </html>
  );
}
